# Generated by Django 5.2 on 2025-04-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carDealer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="company_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="fax",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
